In [262]:
import pandas as pd
import numpy as np

In [263]:
# one dimensional array/sequence of values with associated labels/indices

In [264]:
arr = [1, 0, 1, 2, 2, 2, 3, 4, 5, 5, 4, 4, 5, 7, 7, 7, 6]

# using pandas Series constructor
pd.Series(data=arr)

0     1
1     0
2     1
3     2
4     2
5     2
6     3
7     4
8     5
9     5
10    4
11    4
12    5
13    7
14    7
15    7
16    6
dtype: int64

In [265]:
# numpy n-dimensional array
np.array(arr)

array([1, 0, 1, 2, 2, 2, 3, 4, 5, 5, 4, 4, 5, 7, 7, 7, 6])

In [266]:
d = {'a': 1, 'b': 2, 'c': 3}
pd.Series(data=d)

a    1
b    2
c    3
dtype: int64

In [267]:
d = [45, 56, 77]
ser = pd.Series(data=d,index=["a", "b", "c"])
ser

a    45
b    56
c    77
dtype: int64

In [268]:
ser.index

Index(['a', 'b', 'c'], dtype='object')

In [269]:
d = [45, 56, 77]
ser = pd.Series(data=d,index=[1, 2, 3])
ser

1    45
2    56
3    77
dtype: int64

In [270]:
ser.index

Int64Index([1, 2, 3], dtype='int64')

In [271]:
arr = [1, 0, 1, 2, 2, 2, 3, 4, 5, 5, 4, 4, 5, 7, 7, 7, 6]

# using pandas Series constructor
ser = pd.Series(data=arr, dtype=np.float64)
ser

0     1.0
1     0.0
2     1.0
3     2.0
4     2.0
5     2.0
6     3.0
7     4.0
8     5.0
9     5.0
10    4.0
11    4.0
12    5.0
13    7.0
14    7.0
15    7.0
16    6.0
dtype: float64

In [272]:
ser.dtype

dtype('float64')

In [273]:
ser.index

RangeIndex(start=0, stop=17, step=1)

In [274]:
arr = [1, 0, 1, 2, 2, 2, 3, 4, 5, 5, 4, 4, 5, 7, 7, 7, 6]

# using pandas Series constructor
ser = pd.Series(data=arr, dtype=np.float64, index=pd.RangeIndex(start=4, stop=21, step=1))
ser


4     1.0
5     0.0
6     1.0
7     2.0
8     2.0
9     2.0
10    3.0
11    4.0
12    5.0
13    5.0
14    4.0
15    4.0
16    5.0
17    7.0
18    7.0
19    7.0
20    6.0
dtype: float64

In [275]:
type(ser.index)

pandas.core.indexes.range.RangeIndex

In [276]:
books_list = ["Fooled by Randomness", "On the Origin of Species", "World War Z"]
ser = pd.Series(data=books_list, index=["a_1", "a_2", "a_3"], dtype="string")
ser

a_1        Fooled by Randomness
a_2    On the Origin of Species
a_3                 World War Z
dtype: string

In [277]:
ser.name == None

True

In [278]:
ser.to_frame()

0
a_1      Fooled by Randomness
a_2  On the Origin of Species
a_3               World War Z

In [279]:
ser.name = "my favorite books"

In [280]:
ser

a_1        Fooled by Randomness
a_2    On the Origin of Species
a_3                 World War Z
Name: my favorite books, dtype: string

In [281]:
ser.to_frame()

my favorite books
a_1      Fooled by Randomness
a_2  On the Origin of Species
a_3               World War Z

In [282]:
ser.index.name == None

True

In [283]:
ser.index.name = "my_favorite_indices"
ser

my_favorite_indices
a_1        Fooled by Randomness
a_2    On the Origin of Species
a_3                 World War Z
Name: my favorite books, dtype: string

In [284]:
ser.to_frame()

my favorite books
my_favorite_indices                          
a_1                      Fooled by Randomness
a_2                  On the Origin of Species
a_3                               World War Z

In [285]:
# pd.option.display.min_rows = 40

In [286]:
from string import ascii_lowercase, ascii_uppercase

In [287]:
ascii_lowercase

'abcdefghijklmnopqrstuvwxyz'

In [288]:
ser = pd.Series(data=list(ascii_lowercase), index=[f"Label_{i}" for i in list(ascii_uppercase)])
ser

Label_A    a
Label_B    b
Label_C    c
Label_D    d
Label_E    e
Label_F    f
Label_G    g
Label_H    h
Label_I    i
Label_J    j
Label_K    k
Label_L    l
Label_M    m
Label_N    n
Label_O    o
Label_P    p
Label_Q    q
Label_R    r
Label_S    s
Label_T    t
Label_U    u
Label_V    v
Label_W    w
Label_X    x
Label_Y    y
Label_Z    z
dtype: object

In [289]:
ser = pd.Series(data=list(ascii_lowercase), index=map(lambda x: f"Label_{x}", list(ascii_uppercase)))
ser

Label_A    a
Label_B    b
Label_C    c
Label_D    d
Label_E    e
Label_F    f
Label_G    g
Label_H    h
Label_I    i
Label_J    j
Label_K    k
Label_L    l
Label_M    m
Label_N    n
Label_O    o
Label_P    p
Label_Q    q
Label_R    r
Label_S    s
Label_T    t
Label_U    u
Label_V    v
Label_W    w
Label_X    x
Label_Y    y
Label_Z    z
dtype: object

In [290]:
# find last six letters in series using label indexing 
ser["Label_U":]

Label_U    u
Label_V    v
Label_W    w
Label_X    x
Label_Y    y
Label_Z    z
dtype: object

In [291]:
# find last six letters in series using label indexing 
# end index is inclusive when using labels
ser["Label_U": "Label_Z"]

Label_U    u
Label_V    v
Label_W    w
Label_X    x
Label_Y    y
Label_Z    z
dtype: object

In [292]:
# adding prefixes and suffixes
df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [3, 4, 5, 6]})
df

A  B
0  1  3
1  2  4
2  3  5
3  4  6

In [293]:
df.add_prefix("Label_")

Label_A  Label_B
0        1        3
1        2        4
2        3        5
3        4        6

In [294]:
# iloc indexer
ser.iloc[-6:]

Label_U    u
Label_V    v
Label_W    w
Label_X    x
Label_Y    y
Label_Z    z
dtype: object

In [295]:
# loc indexer
ser.loc["Label_U":]

Label_U    u
Label_V    v
Label_W    w
Label_X    x
Label_Y    y
Label_Z    z
dtype: object

In [296]:
# series after implementing boolean masking using boolean series based on given logical conditions
ser.loc[(ser == "u") | (ser == "x") | (ser == "a")]

Label_A    a
Label_U    u
Label_X    x
dtype: object

In [297]:
# boolean series based on logical conditions
(ser == "u") | (ser == "x") | (ser == "a")

Label_A     True
Label_B    False
Label_C    False
Label_D    False
Label_E    False
Label_F    False
Label_G    False
Label_H    False
Label_I    False
Label_J    False
Label_K    False
Label_L    False
Label_M    False
Label_N    False
Label_O    False
Label_P    False
Label_Q    False
Label_R    False
Label_S    False
Label_T    False
Label_U     True
Label_V    False
Label_W    False
Label_X     True
Label_Y    False
Label_Z    False
dtype: bool

In [298]:
ser.loc[["Label_B", "Label_E", "Label_J"]]

Label_B    b
Label_E    e
Label_J    j
dtype: object

In [ ]:
# usecols and index_col

In [306]:
ser = pd.read_csv("https://andybek.com/pandas-drinks", usecols=["country", "wine_servings"], index_col=["country"]).squeeze()

In [307]:
ser

country
Afghanistan      NaN
Albania         54.0
Algeria         14.0
Andorra        312.0
Angola          45.0
               ...  
Venezuela        3.0
Vietnam          1.0
Yemen            NaN
Zambia           4.0
Zimbabwe         4.0
Name: wine_servings, Length: 193, dtype: float64

In [308]:
ser.is_unique

False

In [309]:
ser.unique()

array([ nan,  54.,  14., 312.,  45., 221.,  11., 212., 191.,   5.,  51.,
         7.,  36.,  42.,   8.,  13.,  35.,  16.,   1.,  94.,   4., 172.,
         3.,   9.,  74., 254., 113., 134., 278.,  26.,   2., 233.,  59.,
        97.,  37., 149., 175., 218.,  28.,  21., 185.,  78., 165., 237.,
        12.,   6., 123.,  62.,  31.,  56., 271.,  18., 128.,  19., 129.,
        23., 339., 167.,  73.,  32.,  71.,  24., 127., 116., 276.,  81.,
       112., 186.,  86., 195.,  84.,  22.])

In [311]:
ser.nunique() == ser.size

False

In [312]:
ser.nunique() == len(ser)

False

In [313]:
ser.nunique() == ser.shape[0]

False

In [314]:
ser.shape[0]

193

In [315]:
ser.count()

162

In [316]:
ser.dropna().shape

(162,)

In [318]:
ser.hasnans

True

In [321]:
ser.loc[ser.isna()]

country
Afghanistan        NaN
Bangladesh         NaN
Bhutan             NaN
Burundi            NaN
North Korea        NaN
Eritrea            NaN
Ethiopia           NaN
India              NaN
Indonesia          NaN
Iran               NaN
Iraq               NaN
Kuwait             NaN
Lesotho            NaN
Libya              NaN
Malaysia           NaN
Maldives           NaN
Marshall Islands   NaN
Mauritania         NaN
Monaco             NaN
Myanmar            NaN
Nepal              NaN
Pakistan           NaN
Rwanda             NaN
San Marino         NaN
Saudi Arabia       NaN
Somalia            NaN
Sri Lanka          NaN
Sudan              NaN
Tajikistan         NaN
Uganda             NaN
Yemen              NaN
Name: wine_servings, dtype: float64

In [322]:
ser.loc[ser.isnull()]

country
Afghanistan        NaN
Bangladesh         NaN
Bhutan             NaN
Burundi            NaN
North Korea        NaN
Eritrea            NaN
Ethiopia           NaN
India              NaN
Indonesia          NaN
Iran               NaN
Iraq               NaN
Kuwait             NaN
Lesotho            NaN
Libya              NaN
Malaysia           NaN
Maldives           NaN
Marshall Islands   NaN
Mauritania         NaN
Monaco             NaN
Myanmar            NaN
Nepal              NaN
Pakistan           NaN
Rwanda             NaN
San Marino         NaN
Saudi Arabia       NaN
Somalia            NaN
Sri Lanka          NaN
Sudan              NaN
Tajikistan         NaN
Uganda             NaN
Yemen              NaN
Name: wine_servings, dtype: float64

In [323]:
ser.loc[ser.isna()].index

Index(['Afghanistan', 'Bangladesh', 'Bhutan', 'Burundi', 'North Korea',
       'Eritrea', 'Ethiopia', 'India', 'Indonesia', 'Iran', 'Iraq', 'Kuwait',
       'Lesotho', 'Libya', 'Malaysia', 'Maldives', 'Marshall Islands',
       'Mauritania', 'Monaco', 'Myanmar', 'Nepal', 'Pakistan', 'Rwanda',
       'San Marino', 'Saudi Arabia', 'Somalia', 'Sri Lanka', 'Sudan',
       'Tajikistan', 'Uganda', 'Yemen'],
      dtype='object', name='country')

In [324]:
ser.isna().sum()

31

In [332]:
# finding nulls using numpy universal functions
ser.loc[np.isnan]

country
Afghanistan        NaN
Bangladesh         NaN
Bhutan             NaN
Burundi            NaN
North Korea        NaN
Eritrea            NaN
Ethiopia           NaN
India              NaN
Indonesia          NaN
Iran               NaN
Iraq               NaN
Kuwait             NaN
Lesotho            NaN
Libya              NaN
Malaysia           NaN
Maldives           NaN
Marshall Islands   NaN
Mauritania         NaN
Monaco             NaN
Myanmar            NaN
Nepal              NaN
Pakistan           NaN
Rwanda             NaN
San Marino         NaN
Saudi Arabia       NaN
Somalia            NaN
Sri Lanka          NaN
Sudan              NaN
Tajikistan         NaN
Uganda             NaN
Yemen              NaN
Name: wine_servings, dtype: float64

In [335]:
ser.loc[ser.notna()]

country
Albania               54.0
Algeria               14.0
Andorra              312.0
Angola                45.0
Antigua & Barbuda     45.0
                     ...  
Vanuatu               11.0
Venezuela              3.0
Vietnam                1.0
Zambia                 4.0
Zimbabwe               4.0
Name: wine_servings, Length: 162, dtype: float64

In [336]:
ser.dropna()

country
Albania               54.0
Algeria               14.0
Andorra              312.0
Angola                45.0
Antigua & Barbuda     45.0
                     ...  
Vanuatu               11.0
Venezuela              3.0
Vietnam                1.0
Zambia                 4.0
Zimbabwe               4.0
Name: wine_servings, Length: 162, dtype: float64

In [337]:
ser.fillna(0)

country
Afghanistan      0.0
Albania         54.0
Algeria         14.0
Andorra        312.0
Angola          45.0
               ...  
Venezuela        3.0
Vietnam          1.0
Yemen            0.0
Zambia           4.0
Zimbabwe         4.0
Name: wine_servings, Length: 193, dtype: float64

In [342]:
ser.describe()

count    162.000000
mean      50.746914
std       76.134917
min        1.000000
25%        3.000000
50%       11.500000
75%       61.250000
max      339.000000
Name: wine_servings, dtype: float64

In [343]:
np.arange(start=0, stop=20, step=2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [344]:
np.arange(start=0, stop=5, step=0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [347]:
ser.quantile(q=np.linspace(start=0, stop=1, num=5))

0.00      1.00
0.25      3.00
0.50     11.50
0.75     61.25
1.00    339.00
Name: wine_servings, dtype: float64

In [356]:
ser.value_counts()

1.0      28
2.0      10
7.0       9
8.0       7
5.0       6
         ..
218.0     1
185.0     1
78.0      1
165.0     1
22.0      1
Name: wine_servings, Length: 71, dtype: int64

In [351]:
ser.mode()

0    1.0
Name: wine_servings, dtype: float64

In [361]:
ser.loc[ser == ser.max()]

country
Portugal    339.0
Name: wine_servings, dtype: float64

In [366]:
for i in ser.loc[ser == ser.min()].index:
    print(i)

Brunei
Cambodia
Canada
Central African Republic
Chad
Comoros
DR Congo
Egypt
Fiji
Gambia
Ghana
Guyana
Haiti
Jordan
Kiribati
Malawi
Mali
Morocco
Namibia
Nicaragua
Niger
Oman
Papua New Guinea
Philippines
Solomon Islands
Thailand
Tanzania
Vietnam


In [368]:
ser + pd.Series({"Albania": 6})

Afghanistan     NaN
Albania        60.0
Algeria         NaN
Andorra         NaN
Angola          NaN
               ... 
Venezuela       NaN
Vietnam         NaN
Yemen           NaN
Zambia          NaN
Zimbabwe        NaN
Length: 193, dtype: float64

In [369]:
ser.add(pd.Series({"Albania": 6}), fill_value=0)

Afghanistan      NaN
Albania         60.0
Algeria         14.0
Andorra        312.0
Angola          45.0
               ...  
Venezuela        3.0
Vietnam          1.0
Yemen            NaN
Zambia           4.0
Zimbabwe         4.0
Length: 193, dtype: float64